using System;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;
using Velopack;
using Velopack.Sources;

namespace PocketMC.Desktop.Infrastructure
{
    /// <summary>
    /// Describes the current state of the auto-update pipeline.
    /// </summary>
    public enum UpdateStage
    {
        Idle,
        Checking,
        Downloading,
        ReadyToRestart,
        UpToDate,
        Error
    }

    /// <summary>
    /// Snapshot broadcasted to subscribers on every state transition.
    /// </summary>
    public sealed class UpdateStatus
    {
        public UpdateStage Stage { get; init; }
        public string? NewVersion { get; init; }
        public double DownloadPercent { get; init; }
        public string? ErrorMessage { get; init; }

        public static UpdateStatus From(UpdateStage stage, string? version = null,
            double percent = 0, string? error = null)
            => new() { Stage = stage, NewVersion = version, DownloadPercent = percent, ErrorMessage = error };
    }

    /// <summary>
    /// Production-ready Velopack update service.
    ///
    /// Design decisions:
    ///   • Uses GithubSource so that the manager resolves the latest GitHub release
    ///     rather than requiring a separate update-feed server.
    ///   • Downloads the update silently in the background; never force-restarts.
    ///   • Exposes <see cref="ApplyUpdateAndRestart"/> so that callers (e.g. the UI)
    ///     decide when to restart — callers should gate this on no running servers.
    ///   • A single <see cref="_semaphore"/> prevents concurrent check/download cycles.
    ///   • Delta packages are used automatically when Velopack finds a matching previous
    ///     full package in the release feed (generated by the CI pipeline).
    /// </summary>
    public sealed class UpdateService : IDisposable
    {
        private const string GitHubRepo = "https://github.com/PocketMC/pocket-mc-windows";
        private const bool IncludePreReleases = false;

        private readonly ILogger<UpdateService> _logger;
        private readonly SemaphoreSlim _semaphore = new(1, 1);
        private UpdateInfo? _pendingUpdate;
        private bool _disposed;

        public event Action<UpdateStatus>? OnStatusChanged;

        public UpdateStage CurrentStage { get; private set; } = UpdateStage.Idle;
        public bool HasPendingUpdate => _pendingUpdate != null;
        public string? PendingVersion => _pendingUpdate?.TargetFullRelease?.Version?.ToString();

        public UpdateService(ILogger<UpdateService> logger)
        {
            _logger = logger;
        }

        // ── Public API ────────────────────────────────────────────────────────────

        /// <summary>
        /// Checks for a new release, downloads it in the background if found,
        /// then moves to <see cref="UpdateStage.ReadyToRestart"/>.
        /// Safe to call repeatedly — concurrent calls are serialised.
        /// </summary>
        public async Task CheckAndDownloadAsync(CancellationToken ct = default)
        {
            if (_disposed) return;

            // Prevent two concurrent update cycles
            if (!await _semaphore.WaitAsync(0, ct))
            {
                _logger.LogDebug("Update check already in progress; skipping.");
                return;
            }

            try
            {
                await RunUpdateCycleAsync(ct);
            }
            finally
            {
                _semaphore.Release();
            }
        }

        /// <summary>
        /// Applies the downloaded update and restarts the application.
        /// Must only be called after <see cref="CurrentStage"/> is
        /// <see cref="UpdateStage.ReadyToRestart"/> and after the caller
        /// has verified no Minecraft servers are running.
        /// </summary>
        public void ApplyUpdateAndRestart()
        {
            if (_pendingUpdate == null)
            {
                _logger.LogWarning("ApplyUpdateAndRestart called but no pending update is staged.");
                return;
            }

            try
            {
                _logger.LogInformation("Applying Velopack update to {Version} and restarting.",
                    _pendingUpdate.TargetFullRelease?.Version);

                var mgr = CreateManager();
                mgr.ApplyUpdatesAndRestart(_pendingUpdate);
                // Control does not return past this line on success.
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Failed to apply Velopack update.");
                Broadcast(UpdateStatus.From(UpdateStage.Error, error: $"Apply failed: {ex.Message}"));
            }
        }

        // ── Internal ──────────────────────────────────────────────────────────────

        private async Task RunUpdateCycleAsync(CancellationToken ct)
        {
            // ── 1. Check ──────────────────────────────────────────────────────────
            Broadcast(UpdateStatus.From(UpdateStage.Checking));

            UpdateInfo? info;
            UpdateManager mgr;

            try
            {
                mgr = CreateManager();
                info = await mgr.CheckForUpdatesAsync().ConfigureAwait(false);
            }
            catch (NotInstalledException)
            {
                // Running from source / not installed via Velopack installer.
                _logger.LogDebug("Velopack update check skipped: app is not installed.");
                Broadcast(UpdateStatus.From(UpdateStage.UpToDate));
                return;
            }
            catch (Exception ex)
            {
                _logger.LogWarning(ex, "Velopack update check failed.");
                Broadcast(UpdateStatus.From(UpdateStage.Error, error: ex.Message));
                return;
            }

            if (info == null)
            {
                _logger.LogInformation("Velopack: already on the latest version.");
                Broadcast(UpdateStatus.From(UpdateStage.UpToDate));
                return;
            }

            string newVersion = info.TargetFullRelease?.Version?.ToString() ?? "unknown";
            _logger.LogInformation("Velopack update available: {Version}. Starting background download.", newVersion);

            // ── 2. Download ───────────────────────────────────────────────────────
            try
            {
                var progress = new Progress<int>(pct =>
                {
                    if (!ct.IsCancellationRequested)
                        Broadcast(UpdateStatus.From(UpdateStage.Downloading, newVersion, pct));
                });

                Broadcast(UpdateStatus.From(UpdateStage.Downloading, newVersion, 0));

                await mgr.DownloadUpdatesAsync(info, progress, ct).ConfigureAwait(false);
            }
            catch (OperationCanceledException)
            {
                _logger.LogInformation("Velopack update download was cancelled.");
                Broadcast(UpdateStatus.From(UpdateStage.Idle));
                return;
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Velopack update download failed.");
                Broadcast(UpdateStatus.From(UpdateStage.Error, newVersion, error: ex.Message));
                return;
            }

            // ── 3. Ready ──────────────────────────────────────────────────────────
            _pendingUpdate = info;
            _logger.LogInformation("Velopack update {Version} downloaded and staged for restart.", newVersion);
            Broadcast(UpdateStatus.From(UpdateStage.ReadyToRestart, newVersion, 100));
        }

        private static UpdateManager CreateManager()
        {
            var source = new GithubSource(GitHubRepo, accessToken: null, IncludePreReleases);
            return new UpdateManager(source);
        }

        private void Broadcast(UpdateStatus status)
        {
            CurrentStage = status.Stage;
            try { OnStatusChanged?.Invoke(status); }
            catch { /* subscribers must not throw */ }
        }

        public void Dispose()
        {
            if (_disposed) return;
            _disposed = true;
            _semaphore.Dispose();
        }
    }
}
