<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows10.0.17763.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="Moq" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
    <Using Include="PocketMC.Domain.Models" />
    <Using Include="PocketMC.Domain.Security" />
    <Using Include="PocketMC.Domain.Storage" />
    <Using Include="PocketMC.Application.Interfaces" />
    <Using Include="PocketMC.Application.Interfaces.Instances" />
    <Using Include="PocketMC.Application.Interfaces.Backups" />
    <Using Include="PocketMC.Application.Services.Shell" />
    <Using Include="PocketMC.Application.Services.Instances" />
    <Using Include="PocketMC.Application.Services.Mods" />
    <Using Include="PocketMC.Application.Services.Networking" />
    <Using Include="PocketMC.Application.Services.Players" />
    <Using Include="PocketMC.Application.Services.Setup" />
    <Using Include="PocketMC.Infrastructure" />
    <Using Include="PocketMC.Infrastructure.Backups" />
    <Using Include="PocketMC.Infrastructure.Backups.Providers" />
    <Using Include="PocketMC.Infrastructure.Configuration" />
    <Using Include="PocketMC.Infrastructure.Diagnostics" />
    <Using Include="PocketMC.Infrastructure.Instances" />
    <Using Include="PocketMC.Infrastructure.Instances.Providers" />
    <Using Include="PocketMC.Infrastructure.Instances.Updates" />
    <Using Include="PocketMC.Infrastructure.Java" />
    <Using Include="PocketMC.Infrastructure.Marketplace" />
    <Using Include="PocketMC.Infrastructure.Mods" />
    <Using Include="PocketMC.Infrastructure.Networking" />
    <Using Include="PocketMC.Infrastructure.OS" />
    <Using Include="PocketMC.Infrastructure.Players" />
    <Using Include="PocketMC.Infrastructure.Power" />
    <Using Include="PocketMC.Infrastructure.Security" />
    <Using Include="PocketMC.Infrastructure.Telemetry" />
    <Using Include="PocketMC.Infrastructure.Tunnel" />
    <Using Include="PocketMC.Infrastructure.Tests.TestSupport.Fixtures" />
    <Using Include="PocketMC.Infrastructure.Tests.TestSupport.Utilities" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PocketMC.Domain\PocketMC.Domain.csproj" />
    <ProjectReference Include="..\PocketMC.Application\PocketMC.Application.csproj" />
    <ProjectReference Include="..\PocketMC.Infrastructure\PocketMC.Infrastructure.csproj" />
  </ItemGroup>
</Project>
